#!/usr/bin/env bash
# Adjust Nginx configuration to listen on port 80
sudo sed -i 's/listen 8080;/listen 80;/g' /etc/nginx/sites-enabled/default
# Test the configuration
sudo nginx -t
# Restart Nginx
sudo service nginx restart

