#!/usr/bin/env bash

# Update package list
sudo apt update -y

# Install Nginx
sudo apt install nginx -y

# Start Nginx without using systemctl (using service command)
sudo service nginx start

# Ensure Nginx starts on port 80 by default
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Create the HTML file with required content
echo "Holberton School" | sudo tee /var/www/html/index.html

